import type { Metadata } from "next";
import type { Locale } from "@/lib/dictionaries";

export const siteConfig = {
  name: "buildroot_ | Digital Products & Engineering",
  description:
    "We build brutalist, high-performance web applications, digital products, and SaaS solutions for modern tech ventures.",
  url: "https://buildroot.co",
  email: "info@buildroot.co",
  links: {
    github: "https://github.com/buildroot-tech",
    // TODO(pre-launch): real company LinkedIn. This feeds the footer and the
    // Organization JSON-LD, so a wrong value ships twice.
    linkedin: "https://linkedin.com/company/buildroot",
  },
  keywords: [
    "Web Development",
    "Digital Products",
    "Software Engineering",
    "SaaS",
    "Next.js",
    "React",
    "Tailwind CSS",
    "Framer Motion",
  ],
};

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  alternates: {
    languages: {
      'en': '/en',
      'es': '/es',
    },
  },
  title: {
    default: siteConfig.name,
    template: `%s | buildroot_`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [
    {
      name: "buildroot_",
      url: siteConfig.url,
    },
  ],
  creator: "buildroot_",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    // Image itself is supplied by the `opengraph-image.tsx` file convention
    // (app/[lang]/opengraph-image.tsx), which Next.js auto-generates and
    // injects into <head> — no static file to keep in sync here.
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    creator: "@buildroot_dev",
    // Image: falls back to the og:image generated by opengraph-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

/**
 * Builds a locale-correct `alternates` block for a given route so the
 * canonical URL and hreflang links always point at the equivalent page in
 * each locale, instead of the generic locale-root fallback in
 * `defaultMetadata`. `path` is the locale-agnostic route, e.g. "/work" or
 * "/work/my-project-id" — pass "" for the homepage.
 */
export function buildAlternates(
  lang: Locale,
  path: string = "",
): Metadata["alternates"] {
  return {
    canonical: `/${lang}${path}`,
    languages: {
      en: `/en${path}`,
      es: `/es${path}`,
    },
  };
}

/** Locale code for `openGraph.locale`, e.g. "en_US" / "es_ES". */
export function ogLocale(lang: Locale): string {
  return lang === "es" ? "es_ES" : "en_US";
}
